//! Remote launcher bash script + JSON status parser.
//!
//! The launcher is generated by `build_launcher_script` and streamed to the
//! remote host via the `RemoteJobBackend::install_launcher` implementation.
//! It is intentionally written for bash 3.2 + POSIX so it runs on Ubuntu and
//! macOS remotes without tweaks. `set -euo pipefail` is enforced and `trap ERR`
//! catches anything unexpected.

mod script;
mod status;
#[cfg(test)]
mod tests;

pub use script::build_launcher_script;
pub use status::{parse_status_json, ParseError};

/// Stable launcher schema version. Bump when the on-disk `status.json` shape
/// changes in a way the Rust-side parser must opt in to.
pub const LAUNCHER_SCHEMA_VERSION: u32 = 1;
